export const currencies = [
  { name: "United States Dollar", value: "USD" },
  { name: "Euro", value: "EUR" },
  { name: "Japanese Yen", value: "JPY" },
  { name: "Pound Sterling", value: "GBP" },
  { name: "Australian Dollar", value: "AUD" },
  { name: "Canadian Dollar", value: "CAD" },
  { name: "Swiss Franc", value: "CHF" },
  { name: "Chinese Yuan", value: "CNY" },
  { name: "Swedish Krona", value: "SEK" },
  { name: "New Zealand Dollar", value: "NZD" },
  { name: "Mexican Peso", value: "MXN" },
  { name: "Singapore Dollar", value: "SGD" },
  { name: "Hong Kong Dollar", value: "HKD" },
  { name: "Norwegian Krone", value: "NOK" },
  { name: "South Korean Won", value: "KRW" },
  { name: "Turkish Lira", value: "TRY" },
  { name: "Brazilian Real", value: "BRL" },
  { name: "South African Rand", value: "ZAR" },
  { name: "Russian Ruble", value: "RUB" },
  { name: "United Arab Emirates Dirham", value: "AED" },
  { name: "Malaysian Ringgit", value: "MYR" },
  { name: "Philippine Peso", value: "PHP" },
  { name: "Argentine Peso", value: "ARS" },
  { name: "Danish Krone", value: "DKK" },
  { name: "Polish Złoty", value: "PLN" },
  { name: "Israeli New Shekel", value: "ILS" },
  { name: "Chilean Peso", value: "CLP" },
  { name: "South African Rand (financial)", value: "ZAL" },
  { name: "CFA Franc BEAC", value: "XAF" },
  { name: "CFA Franc BCEAO", value: "XOF" },
  { name: "CFP Franc", value: "XPF" },
  { name: "Albanian Lek", value: "ALL" },
  { name: "Armenian Dram", value: "AMD" },
  { name: "Azerbaijani Manat", value: "AZN" },
  { name: "Bosnia and Herzegovina Convertible Mark", value: "BAM" },
  { name: "Bulgarian Lev", value: "BGN" },
  { name: "Belarusian Ruble", value: "BYN" },
  { name: "Costa Rican Colón", value: "CRC" },
  { name: "Cuban Convertible Peso", value: "CUC" },
  { name: "Cuban Peso", value: "CUP" },
  { name: "Cape Verdean Escudo", value: "CVE" },
  { name: "Czech Koruna", value: "CZK" },
  { name: "Djiboutian Franc", value: "DJF" },
  { name: "Algerian Dinar", value: "DZD" },
  { name: "Egyptian Pound", value: "EGP" },
  { name: "Eritrean Nakfa", value: "ERN" },
  { name: "Ethiopian Birr", value: "ETB" },
  { name: "Fijian Dollar", value: "FJD" },
  { name: "Falkland Islands Pound", value: "FKP" },
  { name: "Georgian Lari", value: "GEL" },
  { name: "Ghanaian Cedi", value: "GHS" },
  { name: "Gibraltar Pound", value: "GIP" },
  { name: "Gambian Dalasi", value: "GMD" },
  { name: "Guinean Franc", value: "GNF" },
  { name: "Guatemalan Quetzal", value: "GTQ" },
  { name: "Guyanese Dollar", value: "GYD" },
  { name: "Honduran Lempira", value: "HNL" },
  { name: "Croatian Kuna", value: "HRK" },
  { name: "Haitian Gourde", value: "HTG" },
  { name: "Hungarian Forint", value: "HUF" },
  { name: "Indonesian Rupiah", value: "IDR" },
  { name: "Indian Rupee", value: "INR" },
  { name: "Iraqi Dinar", value: "IQD" },
  { name: "Iranian Rial", value: "IRR" },
  { name: "Icelandic Króna", value: "ISK" },
  { name: "Jamaican Dollar", value: "JMD" },
  { name: "Jordanian Dinar", value: "JOD" },
  { name: "Kenyan Shilling", value: "KES" },
  { name: "Kyrgyzstani Som", value: "KGS" },
  { name: "Cambodian Riel", value: "KHR" },
  { name: "Comorian Franc", value: "KMF" },
  { name: "North Korean Won", value: "KPW" },
  { name: "Kuwaiti Dinar", value: "KWD" },
  { name: "Cayman Islands Dollar", value: "KYD" },
  { name: "Kazakhstani Tenge", value: "KZT" },
  { name: "Lao Kip", value: "LAK" },
  { name: "Lebanese Pound", value: "LBP" },
  { name: "Sri Lankan Rupee", value: "LKR" },
  { name: "Liberian Dollar", value: "LRD" },
  { name: "Lesotho Loti", value: "LSL" },
  { name: "Libyan Dinar", value: "LYD" },
  { name: "Moroccan Dirham", value: "MAD" },
  { name: "Moldovan Leu", value: "MDL" },
  { name: "Malagasy Ariary", value: "MGA" },
  { name: "Macedonian Denar", value: "MKD" },
  { name: "Myanmar Kyat", value: "MMK" },
  { name: "Mongolian Tugrik", value: "MNT" },
  { name: "Macanese Pataca", value: "MOP" },
  { name: "Mauritanian Ouguiya", value: "MRU" },
  { name: "Mauritian Rupee", value: "MUR" },
  { name: "Maldivian Rufiyaa", value: "MVR" },
  { name: "Malawian Kwacha", value: "MWK" },
  { name: "Mozambican Metical", value: "MZN" },
  { name: "Namibian Dollar", value: "NAD" },
  { name: "Nigerian Naira", value: "NGN" },
  { name: "Nicaraguan Córdoba", value: "NIO" },
  { name: "Nepalese Rupee", value: "NPR" },
  { name: "Omani Rial", value: "OMR" },
  { name: "Panamanian Balboa", value: "PAB" },
  { name: "Peruvian Nuevo Sol", value: "PEN" },
  { name: "Papua New Guinean Kina", value: "PGK" },
  { name: "Pakistani Rupee", value: "PKR" },
  { name: "Paraguayan Guarani", value: "PYG" },
  { name: "Qatari Rial", value: "QAR" },
  { name: "Romanian Leu", value: "RON" },
  { name: "Serbian Dinar", value: "RSD" },
  { name: "Rwandan Franc", value: "RWF" },
  { name: "Saudi Riyal", value: "SAR" },
  { name: "Solomon Islands Dollar", value: "SBD" },
  { name: "Seychellois Rupee", value: "SCR" },
  { name: "Sudanese Pound", value: "SDG" },
  { name: "Saint Helena Pound", value: "SHP" },
  { name: "Sierra Leonean Leone", value: "SLL" },
  { name: "Somali Shilling", value: "SOS" },
  { name: "Surinamese Dollar", value: "SRD" },
  { name: "South Sudanese Pound", value: "SSP" },
  { name: "São Tomé and Príncipe Dobra", value: "STN" },
  { name: "Syrian Pound", value: "SYP" },
  { name: "Swaziland Lilangeni", value: "SZL" },
  { name: "Thai Baht", value: "THB" },
  { name: "Tajikistani Somoni", value: "TJS" },
  { name: "Turkmenistani Manat", value: "TMT" },
  { name: "Tunisian Dinar", value: "TND" },
  { name: "Tongan Pa'anga", value: "TOP" },
  { name: "Trinidad and Tobago Dollar", value: "TTD" },
  { name: "New Taiwan Dollar", value: "TWD" },
  { name: "Tanzanian Shilling", value: "TZS" },
  { name: "Ukrainian Hryvnia", value: "UAH" },
  { name: "Ugandan Shilling", value: "UGX" },
  { name: "Uruguayan Peso", value: "UYU" },
  { name: "Uzbekistani Som", value: "UZS" },
  { name: "Venezuelan Bolívar", value: "VES" },
  { name: "Vietnamese Dong", value: "VND" },
  { name: "Vanuatu Vatu", value: "VUV" },
  { name: "Samoan Tala", value: "WST" },
  { name: "Silver Ounce", value: "XAG" },
  { name: "Gold Ounce", value: "XAU" },
  { name: "East Caribbean Dollar", value: "XCD" },
  {
    name: "International Monetary Fund (IMF) Special Drawing Rights",
    value: "XDR",
  },
  { name: "Palladium Ounce", value: "XPD" },
  { name: "Platinum Ounce", value: "XPT" },
  { name: "Yemeni Rial", value: "YER" },
  { name: "Zambian Kwacha", value: "ZMW" },
  { name: "Zimbabwean Dollar", value: "ZWL" },
];
